# backend/services/alerts_service.py

alerts = [

    {
        "id": 1,
        "title": "High CPU Usage",
        "description": "Server CPU usage crossed 90%",
        "severity": "Critical",
        "device": "Database Server",
        "status": "Open",
        "time": "2 mins ago",
        "category": "Performance",

        # -------- Enterprise Fields --------
        "incident_id": "INC-2026-1001",
        "priority": "P1",
        "owner": "Network Operations",
        "source": "PRISM AI Engine",
        "impact": "High",
        "root_cause": "Abnormal CPU spike",
        "recommended_action": "Restart compute service and inspect running processes.",
        "resolution_eta": "15 mins",
        "acknowledged": False,
        "escalated": False,
        "history": [
            "CPU exceeded 90%",
            "Alert generated by monitoring engine"
        ]
    },

    {
        "id": 2,
        "title": "Network Delay",
        "description": "High latency detected in network",
        "severity": "Warning",
        "device": "Core Router",
        "status": "Open",
        "time": "10 mins ago",
        "category": "Network",

        "incident_id": "INC-2026-1002",
        "priority": "P2",
        "owner": "Transport Team",
        "source": "Latency Monitor",
        "impact": "Medium",
        "root_cause": "Possible congestion",
        "recommended_action": "Inspect WAN utilization.",
        "resolution_eta": "30 mins",
        "acknowledged": False,
        "escalated": False,
        "history": [
            "Latency crossed threshold",
            "Automatic alert generated"
        ]
    },

    {
        "id": 3,
        "title": "Device Offline",
        "description": "Security camera disconnected",
        "severity": "Critical",
        "device": "Security Camera",
        "status": "Resolved",
        "time": "1 hour ago",
        "category": "Device",

        "incident_id": "INC-2026-1003",
        "priority": "P1",
        "owner": "Security Team",
        "source": "Device Monitor",
        "impact": "High",
        "root_cause": "Power failure",
        "recommended_action": "Restore power supply.",
        "resolution_eta": "Completed",
        "acknowledged": True,
        "escalated": False,
        "history": [
            "Device disconnected",
            "Power restored",
            "Alert resolved"
        ]
    },

    {
        "id": 4,
        "title": "Software Update Required",
        "description": "Firmware update available",
        "severity": "Info",
        "device": "Office Switch",
        "status": "Open",
        "time": "3 hours ago",
        "category": "Maintenance",

        "incident_id": "INC-2026-1004",
        "priority": "P3",
        "owner": "Infrastructure Team",
        "source": "Firmware Scanner",
        "impact": "Low",
        "root_cause": "Outdated firmware",
        "recommended_action": "Schedule firmware upgrade.",
        "resolution_eta": "Next maintenance window",
        "acknowledged": False,
        "escalated": False,
        "history": [
            "Firmware scan completed",
            "Update available"
        ]
    }

]


def get_all_alerts():

    return alerts


def get_alert_by_id(alert_id):

    for alert in alerts:

        if alert["id"] == alert_id:
            return alert

    return None


def get_alert_summary():

    total = len(alerts)

    critical = len(
        [
            alert for alert in alerts
            if alert["severity"] == "Critical"
        ]
    )

    warning = len(
        [
            alert for alert in alerts
            if alert["severity"] == "Warning"
        ]
    )

    resolved = len(
        [
            alert for alert in alerts
            if alert["status"] == "Resolved"
        ]
    )

    return {
        "total": total,
        "critical": critical,
        "warning": warning,
        "resolved": resolved
    }

def resolve_alert(alert_id):

    alert = get_alert_by_id(alert_id)

    if alert:

        alert["status"] = "Resolved"
        alert["acknowledged"] = True

        alert["history"].append(
            "Alert resolved by operator"
        )

        return {

            "message": "Alert resolved successfully",

            "alert": alert

        }

    return {

        "message": "Alert not found"

    }


def acknowledge_alert(alert_id):

    alert = get_alert_by_id(alert_id)

    if alert:

        alert["acknowledged"] = True

        alert["history"].append(
            "Alert acknowledged"
        )

        return {

            "message": "Alert acknowledged",

            "alert": alert

        }

    return {

        "message": "Alert not found"

    }


def escalate_alert(alert_id):

    alert = get_alert_by_id(alert_id)

    if alert:

        alert["escalated"] = True

        alert["priority"] = "P1"

        alert["history"].append(
            "Incident escalated to Level 2 Support"
        )

        return {

            "message": "Alert escalated",

            "alert": alert

        }

    return {

        "message": "Alert not found"

    }


def get_incident_metrics():

    open_alerts = len(
        [
            a for a in alerts
            if a["status"] == "Open"
        ]
    )

    acknowledged = len(
        [
            a for a in alerts
            if a.get("acknowledged")
        ]
    )

    escalated = len(
        [
            a for a in alerts
            if a.get("escalated")
        ]
    )

    critical = len(
        [
            a for a in alerts
            if a["severity"] == "Critical"
        ]
    )

    return {

        "open": open_alerts,

        "acknowledged": acknowledged,

        "escalated": escalated,

        "critical": critical,

        "mttr": "18 mins",

        "sla": "98.7%"

    }