frr version 8.5
frr defaults traditional
hostname pune-branch
no ipv6 forwarding
!
interface eth1
 ip address 10.1.2.2/30
!
interface lo
 ip address 3.3.3.3/32
!
router bgp 65003
 bgp router-id 3.3.3.3
 no bgp ebgp-requires-policy
 neighbor 10.1.2.1 remote-as 65001
 !
 address-family ipv4 unicast
  network 3.3.3.3/32
  neighbor 10.1.2.1 activate
 exit-address-family
!
line vty
!
